Fix RTMP buffer ingest issues
ant-media/Ant-Media-Server-Common pull request #250
Opened 2020-10-12 17:37 UTC by SelimEmre

2020-11-18 15:19 UTC, mekya requested changes

2020-11-18 15:19 UTC, mekya commented on src/main/java/io/antmedia/muxer/MuxAdaptor.java
> +								bufferQueue.poll().close();
Each `poll()` get the header of the queue. It means you get two packets at each time. 
One in `while ((bufferQueue.poll()) != null) ` and one  is  `bufferQueue.poll().close();`

2020-11-18 15:19 UTC, mekya commented on src/main/java/io/antmedia/muxer/MuxAdaptor.java
> +							if(tempPacket != null && tempPacket.size() >= 0) {
I think this is just a patch solution. Do we have to use it? 

If possible, find out the correct cause for this problem. 

Secondly, maybe latest RTMP changes fix this problem. I'm not sure. You may test it.

2020-11-24 19:21 UTC, SelimEmre commented on src/main/java/io/antmedia/muxer/MuxAdaptor.java
> +							if(tempPacket != null && tempPacket.size() >= 0) {
I tested this issue in our latest SNAPSHOT. It seems it's solved with our latest changes.

2020-11-28 20:45 UTC, mekya requested changes

2020-11-28 20:45 UTC, mekya commented on src/main/java/io/antmedia/muxer/MuxAdaptor.java
> +								bufferQueue.poll().close();
There is still problem here

2020-11-30 11:06 UTC, mekya commented
Closing this issue because of this comment 
https://github.com/ant-media/Ant-Media-Server/issues/2540#issuecomment-733197782

2020-11-30 11:06 UTC, closed without merging