Null exception catched
ant-media/Ant-Media-Server-Common pull request #262
Opened 2020-11-24 15:16 UTC by golgetahir

2020-11-24 17:38 UTC, mekya requested changes
Make the code not throw nullpointerexception

2020-11-24 17:38 UTC, mekya commented on src/main/java/io/antmedia/datastore/db/DataStore.java
> +				}catch(Exception e){
Basically NullPointerException is runtime exceptions. It's not recommend to catch the NullPointerException. It's recommend to have the software that does not throw NullPointerException

2020-11-24 19:22 UTC, golgetahir commented on src/main/java/io/antmedia/datastore/db/DataStore.java
> +				}catch(Exception e){
Thank you for your review and attention, Exception is avoided in the last commit instead of being caught.

2020-11-25 07:42 UTC, mekya approved these changes

2020-11-25 07:42 UTC, merged