Fix write_trailer crash by checking if header is written
ant-media/Ant-Media-Server-Common pull request #326
Opened 2021-06-18 12:09 UTC by golgetahir

This PR fixes #https://github.com/ant-media/Ant-Media-Server/issues/3201

2021-06-18 15:51 UTC, mekya requested changes

2021-06-18 15:51 UTC, mekya commented on src/main/java/io/antmedia/muxer/RtmpMuxer.java
> -	private synchronized boolean writeHeader() {
Why do we remove `synchronized`  in writeHeader and writeTrailer ?

They may enter the both methods at the same time.

2021-06-18 15:51 UTC, mekya commented on src/main/java/io/antmedia/muxer/RtmpMuxer.java
> +	private boolean writeHeader() {
I think we also need to include this case. `writeHeader` may be called after `writeTrailer`.
For this case, if `writeTrailer`is callled, we do nothing in the `writeHeader`

2021-06-20 17:10 UTC, golgetahir commented on src/main/java/io/antmedia/muxer/RtmpMuxer.java
> -	private synchronized boolean writeHeader() {
It is done

2021-06-20 17:11 UTC, golgetahir commented on src/main/java/io/antmedia/muxer/RtmpMuxer.java
> +	private boolean writeHeader() {
I have added a trailerWritten volatile boolean for synchronization

2021-06-21 17:25 UTC, mekya commented
Is there a test code for this issue?

2021-06-25 18:16 UTC, mekya approved these changes

2021-06-25 18:26 UTC, merged